<a href="https://colab.research.google.com/github/ValeriaTri01/IA/blob/main/clase1_de_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)

aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux)
print(aux.shape)
print(type(aux))



tmp=np.zeros((4,4))
print(tmp)

tmp=np.full((4,4),5)
print(tmp)


tmp=np.eye(4,4)
print(tmp)

print('--------------')
tmp=np.ones((4,4))
print(tmp)


[1 2 4 5]
(4,)
[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[1.34557803 2.66308037 5.89467329]
 [2.07610507 8.71949059 6.27382153]
 [8.84379385 0.57863251 4.84862336]]


In [ ]:
print(tmp [:2, :2])

[[1.34557803 2.66308037]
 [2.07610507 8.71949059]]


In [ ]:
print(tmp [:2, 1:3])

[[2.66308037 5.89467329]
 [8.71949059 6.27382153]]


In [ ]:
print(tmp [1,1])
print(tmp [2,2])

8.719490587817035
4.848623364035496


In [ ]:
mask=tmp>5
print(mask)

mask=tmp>5
print(tmp[mask])

[[False False  True]
 [False  True  True]
 [ True False False]]
[5.89467329 8.71949059 6.27382153 8.84379385]


In [ ]:
mask =(tmp>=2)& (tmp<=4)
print(tmp[mask])

[2.66308037 2.07610507]


In [ ]:
integer_array = np.random.randint(0, 10,(4,4))
print(integer_array)

[[4 1 0 6]
 [1 4 7 7]
 [0 8 2 5]
 [2 4 1 9]]


In [ ]:
arreglo = np.random.randint(1, 101, size=(4,4))
print("Arreglo original:")
print(arreglo)

mascara_pares =arreglo % 2==0

numeros_pares =[mascara_pares]

print()

Arreglo original:
[[93 37 72  9]
 [42 69 53 43]
 [93 47  1 85]
 [48 32 96 27]]

