<a href="https://colab.research.google.com/github/ValeriaTri01/IA/blob/main/Copia_de_NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version
import numpy as np
# your code here
pass
print("NumPy version:", np.__version__)

NumPy version: 1.23.5


In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
array_1d = np.arange(10)
print(array_1d)
pass

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0

# Create a random vector of size 10 crear el valor aletorio
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector valor maximo del vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0 remplezar el valor
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)


pass

Random vector with the maximum value replaced by 0:
[0.86439707 0.10756816 0.         0.08609488 0.31146744 0.66414153
 0.95750484 0.88604415 0.16563283 0.32251967]


In [ ]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Access and print the number 8
number_8 = arr[1, 2]
print(number_8)
pass

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use array indexing to extract the elements [3, 4, 5] estraer los elementos
sub_array = arr[2:5]

# Print the extracted sub-array
print(sub_array)

pass

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# extract the last 4 numbers  last ultimos
last_four = arr[-4:]

# Print the last 4 numbers
print(last_four)
pass

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s Crea una matriz numérica de 3 × 3 de todos los True
# your code here

array_of_trues = np.ones((3, 3), dtype=bool)

print(array_of_trues)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here

# Assuming you have a NumPy array named 'arr' Suponiendo que tienes una matriz NumPy llamada 'arr'
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Extract all odd numbers from arr Extraemos todos los números impares de arr
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)
pass

[1 3 5 7 9]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆) # Crea un vector con valores que van de 10 a 49

result_vector = np.arange(10, 50)

print(result_vector)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last) Invertir un vector (el primer elemento pasa a ser el último)

# Suponiendo que tienes una matriz NumPy llamada 'original_vector'
vector_original = np.array([1, 2, 3, 4, 5])

# Invertir el vector
vector_invertido = np.flip(vector_original)

print(vector_invertido)
pass

[5 4 3 2 1]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
# Crea una matriz de 10x10 con valores enteros aleatorios y encuentra los valores mínimo y máximo

# Create a 10x10 array with random integer values
random_array = np.random.randint(low=0, high=100, size=(10, 10))

# Find the minimum and maximum values in the array
minimum_value = np.min(random_array)
maximum_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("\nMinimum Value:", minimum_value)
print("Maximum Value:", maximum_value)

pass

Random Array:
[[89 29 86  2 23 64 65 71 15 95]
 [69  9 83 98 96 45 99 70 44  8]
 [ 9 16 77 97 46 81 16 35 28  4]
 [32 60 61 59 21 57 74 77  0 60]
 [ 9 34 94 92 38 34 12 35 47 86]
 [91 25 10 89 66 14 63 41 22 74]
 [28 81 56 26  3 12 69 88 94 91]
 [17 52 40  8 40 99 30 49 24 32]
 [79 42 86 94 69 46 93 21 99 63]
 [75 35 42 28  8 45 97  6 76 49]]

Minimum Value: 0
Maximum Value: 99


In [ ]:
# Create a 3x3x3 array with random values
random_3d_array = np.random.rand(3, 3, 3)

print(random_3d_array)
pass

[[[0.12345517 0.85505174 0.60093754]
  [0.07603193 0.81307047 0.11699313]
  [0.92062725 0.11824338 0.25584141]]

 [[0.66170271 0.91983366 0.74833901]
  [0.8300788  0.89604702 0.86997602]
  [0.68189467 0.63333051 0.46291561]]

 [[0.61602425 0.74832278 0.82015427]
  [0.26545534 0.47970297 0.94347618]
  [0.94799658 0.17242676 0.76999398]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here

# Suponiendo que tienes una matriz NumPy llamada 'arr'
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reemplazar todos los números impares en arr con -1
arr[arr % 2 != 0] = -1

print(arr)
pass

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
# Create an array of type float
# Crea una matriz de tipo float

float_array = np.array([1.0, 2.5, 3.7], dtype=float)

print(float_array)
pass

[1.  2.5 3.7]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows: # Convertir una matriz 1D en una matriz 2D con 2 filas
# your code here

# Suponiendo que tienes una matriz 1D llamada 'original_array'
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convertir la matriz 1D a una matriz 2D con 2 filas
reshaped_array = np.reshape(original_array, (2, -1))
print(reshaped_array)
pass

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)

# Given arrays matrices dadas
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find common values between Z1 and Z2  Encuentra valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("Common Values:", common_values)
pass

Z1: [0 4 6 3 5 7 9 1 3 9]
Z2: [9 6 2 6 8 2 6 2 2 7]
Common Values: [6 7 9]


In [ ]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)


# Given arrays
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if arrays A and B are equal comprobar si los arreglo A y B son iguales
are_equal = np.array_equal(A, B)

print("A:", A)
print("B:", B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


pass

A: [0 1 1 0 0]
B: [1 0 1 0 0]
Arrays A and B are not equal.


In [ ]:
# Stack arrays a and b vertically aplicar los arreglos a y b veryicalmente
# your code here


# Assuming you have two arrays 'a' and 'b' suponiendo que tienes dos matrices a y b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays 'a' and 'b' vertically
stacked_array = np.vstack((a, b))

print("Array 'a':", a)
print("Array 'b':", b)
print("Stacked Array (Vertically):")
print(stacked_array)

pass

Array 'a': [1 2 3]
Array 'b': [4 5 6]
Stacked Array (Vertically):
[[1 2 3]
 [4 5 6]]


In [ ]:
# Stack the arrays a and b horizontally. aplicar los arreglos a y b horizontal
# your code here


# Assuming you have two arrays 'a' and 'b'
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays 'a' and 'b' horizontally
stacked_array = np.hstack((a, b))

print("Array 'a':", a)
print("Array 'b':", b)
print("Stacked Array (Horizontally):", stacked_array)

pass

Array 'a': [1 2 3]
Array 'b': [4 5 6]
Stacked Array (Horizontally): [1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)

# Obtener todos los elementos entre 5 y 10 del array tmp
resultado = tmp[(tmp >= 5) & (tmp <= 10)]

print(resultado)
# pass

[ 5  6  7  8  9 10]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)


5

In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

# Establecer una semilla para reproducibilidad (opcional)
np.random.seed(42)

# Crear una matriz 2D de tamaño 5x3 con números decimales aleatorios entre 5 y 10
matriz_aleatoria = np.random.uniform(5, 10, size=(5, 3))

# Imprimir la matriz resultante
print(matriz_aleatoria)

[[6.87270059 9.75357153 8.65996971]
 [7.99329242 5.7800932  5.7799726 ]
 [5.29041806 9.33088073 8.00557506]
 [8.54036289 5.10292247 9.84954926]
 [9.1622132  6.06169555 5.90912484]]
